services:
  db:
    image: postgres:15
    container_name: medusa-db
    restart: always
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: medusa
    ports:
      - "5432:5432"
    volumes:
      - medusa_db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: medusa-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  medusa_db_data:
